name: egenet
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - torch
      - torchvision
      - torchaudio
      - torch_geometric
      - lightning
      - easydict
      - pandas
      - rdkit
